"""Regenerate the guard's verb lexicon from the pinned Zemberek dictionary.

Usage: python3 scripts/generate-turkish-stems.py /path/to/master-dictionary.dict
Source revision and license are recorded in the generated module and implementation guide.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE_REVISION = "037202c7e18b977c95181a76db05cb1e95846554"
stems = set()
for line in Path(sys.argv[1]).read_text(encoding="utf-8").splitlines():
    # An unannotated -mak/-mek entry is a verb. Explicit homonymous nouns are not.
    match = re.match(r"^([a-zçğıöşü]+)m[ae]k(?:\s|$)", line)
    if not match or ("P:" in line and "P:Verb" not in line):
        continue
    stem = match[1]
    stems.add(stem)
    if "Voicing" in line and "NoVoicing" not in line and stem[-1] in "pçtk":
        stems.add(stem[:-1] + {"p": "b", "ç": "c", "t": "d", "k": "ğ"}[stem[-1]])
words = sorted(stems)
rows = [" ".join(words[i:i + 12]) for i in range(0, len(words), 12)]
header = f"""// Derived verb stems from Zemberek-NLP, revision {SOURCE_REVISION}.
// Copyright 2018 Ahmet A. Akın, Mehmet D. Akın. Apache-2.0; see ../licenses/zemberek-Apache-2.0.txt.
// Source: morphology/src/main/resources/tr/master-dictionary.dict; modified to keep verb stems and voiced variants only.
// Generated by scripts/generate-turkish-stems.py. This lexicon is not a morphological disambiguator.
export const TURKISH_VERB_STEMS = new Set(`
"""
(ROOT / "extension/lib/turkish-verbs.mjs").write_text(header + "\n".join(rows) + "\n`.trim().split(/\\s+/u));\n", encoding="utf-8")
print(f"Generated {len(words)} verb stems")
